import { Link } from 'react-router-dom';
import LegalLayout from './LegalLayout';

const REPO_URL = 'https://github.com/anubhavgpta/bankai-security-remediation-platform';

export default function Terms() {
  return (
    <LegalLayout kicker="Legal" title="Terms of Service" updated="July 23, 2026">
      <h2>1. Agreement</h2>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the hosted Bankai
        service (&ldquo;Bankai&rdquo;, &ldquo;the Service&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) — a security remediation platform that
        turns vulnerability scan output into triaged findings, tickets, and CI-verified pull
        requests. By creating an account or using the Service, you agree to these Terms and to the{' '}
        <Link to="/privacy">Privacy Policy</Link>. If you are using Bankai on behalf of an
        organization, you represent that you have authority to bind that organization to these
        Terms.
      </p>

      <h2>2. The Service</h2>
      <p>
        Bankai ingests security findings (from uploaded scan reports or AI-assisted repository
        scans), helps you triage them, creates tickets, and — when you connect GitHub — opens
        remediation branches and pull requests with AI-generated fix proposals, optionally verified
        by a CI pipeline. Bankai can also synchronize tickets with a connected Jira project.
      </p>

      <h2>3. Your account</h2>
      <ul>
        <li>You must provide accurate account information and keep your credentials secure.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>
          You may sign in with an email and password or through Google or GitHub single sign-on.
        </li>
      </ul>

      <h2>4. Your content and repositories</h2>
      <p>
        You retain all rights to the content you bring to Bankai — scan reports, findings,
        repository code, tickets, and project data (&ldquo;Your Content&rdquo;). You grant us only the limited
        rights needed to operate the Service: to store, process, and display Your Content to you
        and your project members, and to transmit relevant portions to the integrations and
        subprocessors described in the <Link to="/privacy">Privacy Policy</Link>.
      </p>
      <p>
        You are responsible for ensuring you have the right to connect any repository, Jira
        project, or other resource, and that scanning and modifying it does not violate any
        third-party agreement.
      </p>

      <h2>5. Integrations</h2>
      <p>
        Connecting GitHub, Jira, or other third-party services is optional and subject to those
        services&rsquo; own terms. You authorize Bankai to act on your behalf within the scope of the
        credentials you provide — for example creating branches, committing fixes, opening pull
        requests, managing webhooks, and creating or transitioning Jira issues. You can revoke
        these credentials at any time from your project settings or from the third-party service.
      </p>

      <h2>6. AI-generated output</h2>
      <ul>
        <li>
          Fix proposals, triage assessments, and related output are generated by AI models and may
          be incorrect, incomplete, or inappropriate for your codebase.
        </li>
        <li>
          <strong>A human must review all AI output before relying on it.</strong> Bankai never
          merges pull requests automatically, and fixes the AI itself was uncertain about are
          explicitly labeled low-confidence.
        </li>
        <li>
          You are solely responsible for code you merge and deploy, including AI-proposed changes.
        </li>
      </ul>

      <h2>7. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>scan, analyze, or modify repositories or systems you are not authorized to access;</li>
        <li>use the Service to develop, distribute, or deploy malicious code;</li>
        <li>interfere with or disrupt the integrity or performance of the Service;</li>
        <li>attempt to access data belonging to other users or projects;</li>
        <li>resell or provide the hosted Service to third parties without our consent.</li>
      </ul>

      <h2>8. Open source and self-hosting</h2>
      <p>
        Bankai&rsquo;s source code is available under the{' '}
        <a href={`${REPO_URL}/blob/main/LICENSE`} target="_blank" rel="noreferrer">
          MIT License
        </a>
        . These Terms govern only the hosted Service; self-hosted deployments are governed by the
        MIT License alone, and you are responsible for operating them.
      </p>

      <h2>9. Availability and changes</h2>
      <p>
        The Service is provided free of charge and on an &ldquo;as available&rdquo; basis. We may modify,
        suspend, or discontinue the Service (or any part of it) at any time. We will make
        reasonable efforts to announce material changes in advance, but are not obligated to do
        so for a free service.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time. We may suspend or
        terminate accounts that violate these Terms or that create security, legal, or technical
        risk for the Service or other users.
      </p>

      <h2>11. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;, WITHOUT WARRANTY OF ANY KIND, EXPRESS
        OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
        PARTICULAR PURPOSE, AND NON-INFRINGEMENT. BANKAI DOES NOT WARRANT THAT IT WILL DETECT ALL
        VULNERABILITIES, THAT AI-GENERATED FIXES ARE CORRECT OR COMPLETE, OR THAT THE SERVICE WILL
        BE UNINTERRUPTED OR ERROR-FREE.
      </p>

      <h2>12. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR
        GOODWILL, ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE. OUR AGGREGATE LIABILITY FOR
        ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED ONE HUNDRED US DOLLARS (USD $100).
      </p>

      <h2>13. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. The &ldquo;Last updated&rdquo; date above reflects the
        most recent revision, and continued use of the Service after a revision takes effect
        constitutes acceptance of the revised Terms.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms can be raised on the{' '}
        <a href={`${REPO_URL}/issues`} target="_blank" rel="noreferrer">
          Bankai GitHub repository
        </a>
        .
      </p>
    </LegalLayout>
  );
}
