-- Self-healing CI retry loop: tracks how many times Bankai has generated a
-- fix for this ticket (1 = the original fix-pr.job.ts fix, 2/3 = automatic
-- retries after a CI failure regenerated by fix-retry.job.ts). Capped at 3
-- total attempts in application code (webhook.controller.ts / fix-retry.job.ts)
-- — this column is just the counter, not itself a constraint on the max.

alter table public.tickets add column if not exists ci_fix_attempt integer not null default 1;
